website/tools/ballerinaByExample/templates/example.tmpl
website/tools/guides/ballerina.io-guide-theme/base.html

Remove highlighting in console output section
Change text from "GET THE CODE" to "REFER GITHUB"

Remove highlighting in console output section

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

This is a first draft of the document on how to extend and customize Ballerina. This document is for ecosystem and third parties to use to learn how they can start customizing Ballerina for their own end users.
1. How to write client connectors
2. How to write server listeners
3. How to write custom annotations

How To Extend Ballerina Learn Doc - Initial Submission

---

website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md

Use Ballerina service instead of Ballerina program.
Here we are explaining about the observability of a Ballerina service.

Use Ballerina service instead of Ballerina program 

---

website/two-column-pages/docs/learn/quick-tour.md

This PR adds a description to the "service" concept when it appears first in the quick start guide so that novice user gets an understanding of the concept well.

Add a service description to the quick tour guide

---

website/two-column-pages/docs/learn/quick-tour.md

This PR adds a description to the "endpoint" construct when it appears first in the quick start guide.

Add a description to the endpoint construct within quick start guide

---

website/two-column-pages/docs/learn/quick-tour.md

This PR adds a description to the "connector" concept at first appearance so that novice user gets an understanding of the concept.

Add connector description to quick start guide

---

website/two-column-pages/docs/learn/quick-tour.md

This is a fix for UI issue on https://ballerina.io/learn/quick-tour/ page.
The `bash` keyword is shown in the website as it is before showing the bash command.

Fix for a UI issue on website

---

playground-widget/resources/docker/launcher/Dockerfile
playground-widget/resources/docker/launcher/netty-transports.yml

> Fix a security vulnerability. 
> N/A
> This Dockerfile further can be improved to reduce the layers. This is a quick fix to get rid of running container as the root user. The same fix needs to be applied to all other docker files too.
- Any checklist items to be verified before production deployment? It is required to test the complete flow once all docker images are updated to run as ballerinauser
- Special styling concerns? N/A
- Related media files? N/A

run launcher container as a ballerinauser instead of root

---

website/two-column-pages/docs/learn/quick-tour.md
website/two-column-pages/docs/open-source.md

Added star and watch button placeholders along with improved section header and text
Please review before commit for both design elements and content
Both quick tour page and open source page has been updated. 
On quick tour, it is in a new section. 
On open source page, it is added within the section Source Code where we point to the repo.

Adding star and watch actions to for GitHub repo

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

> This PR will remove redundant ballerina commands and content.

 Remove redundant ballerina commands and content in ballerina.io

---

website/two-column-pages/docs/help.md

The link was not correct - was taking to the page that required to already have an account. Changed it to the proper landing page where you can sign up.

Fix Slack link

---

website/pom.xml
website/tools/build-bbe.sh

> BBE samples will be cloned from the repo instead of from the Nexus. This will make the BBE releases independent from core releases. 
> 
> -

Fetching BBE from the repo

---

playground-widget/web/src/components/editor/CodeEditor.js

$subject
This is done by making lineDecorationsWidth 0

Fix extra space showing between the line number and code

---

playground-widget/web/src/components/editor/CodeEditor.css
playground-widget/web/src/components/editor/CodeEditor.js

This was increased after updating monaco editor

Reduce width of the line-numbers panel to the original width

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Package structure needs the following changes to build successfully.
1) Remove empty resources and tests directories which do not need. If you have empty directories, build command will be failed.
2) Package.balo will be created with .ballerina/repo/[org-name]/[package-name]/[version]/[package-name].zip. It will not be in target/ directory.
3) When you have reserved word in package name , project build fails as well.
ex. packages.can.include.dots.in.dir.name here 'in is a reserved word hence build will be failed.
Hence rename  'packages.can.include.dots.in.dir.name' to 'packages.can.include.dots.inthe.dir.nam

Fix outdated content in b7a structure doc

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Ballerina does not support specifying the package version in the `import` package declaration. This will be added in the future.

Remove version keyword in import declaration

---

website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md

Rename ballerina file name to `hello_world_service.bal` as it is used throughout the guide.

Rename ballerina file name in how to observe ballerina code

---

website/two-column-pages/docs/learn/tools-ides.md

This will replace "Swagger" with "OpenAPI" and fix any broken navigation for the titles.
* https://github.com/ballerina-platform/ballerina-www/pull/1413
* https://github.com/ballerina-platform/ballerina-www/pull/1411

Fix OpenAPI code generator title and links

---

website/two-column-pages/docs/security.md

This is to replace all occurrences of the usage of security@wso2.com email address in the Ballerina website to security@ballerina.io.
https://github.com/ballerina-platform/ballerina-www/pull/1436/files

Change all security@wso2.com occurrences

---

website/two-column-pages/docs/learn/tools-ides.md

This is to add 2 buttons in [1] to direct users to the IDEA and VSCode pages.
[1] https://ballerina.io/learn/tools-ides/

Add buttons of the IDE logos

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

This is to document the `--skiptests` flag for the `ballerina build` command.
Fixes lang-issue-13935.

Document the --skiptests flag

---

website/two-column-pages/docs/learn/how-to-document-ballerina-code.md
website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md
website/two-column-pages/docs/learn/quick-tour.md

This is to replace the `ballerina create` command with `ballerina add` in the content of the Ballerina website.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/17897.

Replace the `ballerina create` command with `ballerina add`

---

website/two-column-pages/docs/learn/quick-tour.md

Replace separate build and run commands with single module run step.
1. We no longer generate .jar's in the module directory (now it's all in project's target/bin)
2. I think it's better to use simpler step in `quick-tour`

Use ballerina module run command

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

> The page mentioned above contained outdated and invalid usages of the config API. This PR updates that page.

Fix -e usages in how to secure Ballerina code page

---

website/two-column-pages/docs/learn/style-guide/README.md
website/two-column-pages/docs/learn/style-guide/definitions.md
website/two-column-pages/docs/learn/style-guide/expressions.md
website/two-column-pages/docs/learn/style-guide/operators_keywords_and_types.md

This will update the style guideline to have a rule for type init and fix some typos in the examples.

Add formatting rule for type init in style guide
