ballerina-platform/ballerina-www

website/main-pages/ballerina.io-website-theme/footer.html
website/main-pages/docs/license-of-site.md
website/main-pages/docs/terms-of-service.md

Updated footer.html and added .md files for Terms of Service and website license.

Updated footer.html and added .md files

---

website/main-pages/docs/learn.md

Added content for the Learn page

Added content for the Learn page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/ballerina.io-two-col-theme/css/ballerina-io-docs.css
website/two-column-pages/ballerina.io-two-col-theme/navigation.html

Deleted the site folder

---

website/two-column-pages/docs/open-source.md

Adding the open source page to the website repo.

Adding open source page

---

website/two-column-pages/docs/learn.md

Added video channel link

---

website/pom.xml

Fix widget

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/footer.html
website/main-pages/docs/philosophy.md

Updated two col theme

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/img/gray-arrow-left.svg
website/main-pages/ballerina.io-website-theme/img/gray-arrow-right.svg
website/main-pages/mkdocs.yml
website/tools/ballerinaByExample/templates/example.tmpl
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/ballerina.io-two-col-theme/footer.html
website/two-column-pages/ballerina.io-two-col-theme/navigation.html

Updated the theme

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/ballerinaByExample/templates/index.tmpl

fixed the bread crums

---

website/two-column-pages/docs/help.md

New Help page content

---

website/main-pages/docs/index.md
website/main-pages/docs/philosophy.md
website/two-column-pages/docs/help.md
website/two-column-pages/docs/learn.md

Fixed numerous links and typos

Fixed numerous links and typos

---

website/two-column-pages/ballerina.io-two-col-theme/navigation.html

Updated the 2col menu

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/two-column-pages/ballerina.io-two-col-theme/base.html

Added search script tags and updated the search form in the navigation header

Added search script tags and updated the search form

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/tools/ballerinaByExample/templates/example.tmpl

Updated BBE

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update the footer

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/docs/philosophy.md

Updated guides description 
Changed the order of loading search libraries

Search and philosophy page updates

---

website/main-pages/docs/philosophy.md
website/two-column-pages/docs/learn.md
website/two-column-pages/docs/license-of-site.md

Edits to text

---

website/main-pages/ballerina.io-website-theme/css/help-page.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/two-column-pages/docs/help.md

Fixed the help page

---

website/main-pages/docs/security.md
website/two-column-pages/docs/open-source.md

Make the text more Ballerina-specific

---

website/two-column-pages/docs/learn.md
website/two-column-pages/docs/quick-tour.md

Updated learn page and added quick tour

Updated learn page and added quick tour

---

website/two-column-pages/docs/learn/quick-tour.md
website/two-column-pages/mkdocs.yml

Moved quick tour page to the learn folder

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/download-page.css

Fixed the api docs

---

website/two-column-pages/docs/open-source.md

Shorten text, avoid contribution guide duplication

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/tools/ballerinaByExample/templates/example.tmpl

Updated the BBE theme

---

website/two-column-pages/docs/downloads/release-notes.md

Update release notes .md file

---

website/tools/guides/index.html

Added the guides home page

---

website/two-column-pages/docs/open-source.md

Fix styling

---

website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/tools/generate.go

Fix github link button
Created the github link while generating doc contents
When user clicks on github icon, it should open the the sample in github

Fix github link

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css

Fixed the layout issues

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/docs/downloads.md

Download page style fixes & content updates

Download page fixes

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/tools/generate.go

When there are are multiple console output sections for samples, only last output section is colored in grey. Purpose of this commit it to fix it and make all console output sections grey

Make console output section grey

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/tools/generate.go

Enable hover only for code segments which contains docs

Enable hover only for code segments which has docs

---

website/main-pages/ballerina.io-website-theme/breadcrumbs.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/docs/index.md
website/two-column-pages/ballerina.io-two-col-theme/breadcrumbs.html

Layout updates

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/img/green-arrow.svg
website/main-pages/docs/index.md

IFrame and BBE updates

---

website/tools/guides/ballerina.io-guide-theme/base.html
website/tools/guides/ballerina.io-guide-theme/breadcrumbs.html
website/tools/guides/mkdocs.yml

Set correct git urls on guides section

Set correct git urls on guides section

---

api-docs/docs/auth.authz.html
api-docs/docs/auth.authz.permissionstore.html
api-docs/docs/auth.basic.html
api-docs/docs/auth.html
api-docs/docs/auth.jwtAuth.html
api-docs/docs/auth.userstore.html
api-docs/docs/builtin.html
api-docs/docs/caching.html
api-docs/docs/collections.html
api-docs/docs/config.html
api-docs/docs/data.sql.html
api-docs/docs/file.html
api-docs/docs/http.html
api-docs/docs/http.swagger.html
api-docs/docs/internal.html
api-docs/docs/io.html
api-docs/docs/jwt.html
api-docs/docs/log.html
api-docs/docs/mime.html
api-docs/docs/net.grpc.html
api-docs/docs/runtime.html
api-docs/docs/test.html
api-docs/docs/time.html
api-docs/docs/transactions.html
api-docs/docs/util.html
website/main-pages/ballerina.io-website-theme/img/copy-icon-line.svg

Update the new API docs

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Fixed the api styles

---

api-docs/docs/util.html

Update api docs

---

website/main-pages/ballerina.io-website-theme/css/archived-page.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/docs/downloads.md
website/main-pages/mkdocs.yml
website/three-column-pages/mkdocs.yml
website/two-column-pages/docs/downloads/archived.md
website/two-column-pages/mkdocs.yml

> Added archived page + did some tweaks on download page

Download page tweaks

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-guides.css
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/guides/ballerina.io-guide-theme/base.html

Fix "GET THE CODE" section in guides

Fix "GET THE CODE" section in guides

---

website/two-column-pages/docs/open-source.md

Added H3, fixed Title Case for headers

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/main-pages/ballerina.io-website-theme/samples/asynchronous-execution.txt
website/main-pages/ballerina.io-website-theme/samples/docker-and-kubernetes.txt
website/main-pages/ballerina.io-website-theme/samples/full-language.txt
website/main-pages/ballerina.io-website-theme/samples/json-and-xml.txt
website/main-pages/ballerina.io-website-theme/samples/rest-services-run.txt
website/main-pages/ballerina.io-website-theme/samples/rest-services.txt
website/main-pages/ballerina.io-website-theme/samples/type-safety.txt
website/main-pages/docs/philosophy.md

Added monaco editor to philosophy page.

Adding syntax editor to the philosophy page

---

website/main-pages/ballerina.io-website-theme/css/archived-page.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/css/help-page.css

Fixed some styling issues

---

pom.xml
website/main-pages/build.sh
website/three-column-pages/build.sh
website/tools/guides/build.sh
website/tools/search-generator.py
website/tools/search/search-generator.py
website/two-column-pages/build.sh

> Fixed build fail on windows + Non file copying issue in the final bundle
NOTE:- In order to fix non file copying issue, I had to remove 'rsync' in the build shell scripts. As it has a supporting issue in windows. Please confirm if this will not break on linux & mac before merging the PR.

Fixed build failure on windows

---

pom.xml
website/main-pages/build.sh
website/three-column-pages/build.sh
website/tools/guides/build.sh
website/tools/search-generator.py
website/tools/search/search-generator.py
website/two-column-pages/build.sh

Revert https://github.com/ballerina-platform/ballerina-www/pull/160/

Revert https://github.com/ballerina-platform/ballerina-www/pull/160/

---

website/two-column-pages/ballerina.io-two-col-theme/base.html

> Fixed two-column-pages layout issues

Fixed two-column-pages layout issues

---

website/main-pages/docs/philosophy.md

Fixing the broken Ballerina by Examples section @ phylosophy page.

Fixing the broken Ballerina by Examples section in the phylosophy page

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Hiding the subscribe form after the submission to display the status message

Hiding the subscribe form after the submission

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fixed the home page download button bg image

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

> Fixed heading tags content styling in two-column-pages

Fixed heading tags content styling in two-column-pages

---

playground-widget/config/webpack.config.js
playground-widget/package-lock.json
playground-widget/package.json
playground-widget/src/components/console/Console.css
playground-widget/src/components/console/Console.js
playground-widget/src/index.ejs
playground-widget/src/index.js

 Fix playground widget rendering on IE11 & other old browsers

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fixed the subscribe button thank you message

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

> Added styling for additional heading on two-column-pages

Added styling for additional heading on two-column-pages

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

> Changed inline-code block styling

Changed inline-code block styling

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Removed the default span to avoid taking an empty space and dynamically generating it upon the subscribe form submission

Dynamically generating the status message span

---

website/two-column-pages/docs/help.md
website/two-column-pages/docs/learn.md
website/two-column-pages/docs/learn/getting-started.md
website/two-column-pages/docs/learn/quick-tour.md

Quick tour and getting started updates

---

website/main-pages/ballerina.io-website-theme/css/help-page.css
website/tools/ballerinaByExample/templates/index.tmpl

Fixed the help page width

---

website/guides/index.html
website/tools/guides/ballerina.io-guide-theme/base.html
website/tools/guides/build.sh

[bbg]Fetch search content from root, Update relative paths while moving README/index.html

[bbg]Fetch search content from root, Update relative paths while moving README/index.html

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/docs/philosophy.md

Updated the philosophy page image and font styles

---

website/two-column-pages/docs/open-source/slack.md
website/two-column-pages/mkdocs.yml

> This page will allow users to request Slack invitations to the Ballerina Slack channel

Slack request invite page - initial commit

---

website/main-pages/ballerina.io-website-theme/css/archived-page.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/docs/downloads.md
website/two-column-pages/docs/downloads/archived.md

> Fixed search box styling in two-column-pages
> Download/Archived pages style fixes & tweaks

Inner page style fixes

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/add-monaco.js
website/main-pages/ballerina.io-website-theme/js/quick-tour.js
website/main-pages/docs/philosophy.md
website/two-column-pages/docs/learn/quick-tour.md

Adding monaco editor to the Quick Tour Page and add links to the Open Source section in the Philosophy page

Adding monaco editor to the Quick Tour Page

---

website/tools/guides/index.html

Updated the BBG home page

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

> BBG layout will have the same layout as BBE

BBG listing layout updated

---

website/two-column-pages/docs/open-source.md

> Fixed content: Ordered list not working issue in Open Source page

Fixed content: Ordered list not working issue in Open Source page

---

website/tools/guides/ballerina.io-guide-theme/base.html
website/tools/guides/ballerina.io-guide-theme/breadcrumbs.html
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/ballerina.io-two-col-theme/breadcrumbs.html
website/two-column-pages/mkdocs.yml

Fix breadcrumbs in bbg and quick tour

Fix breadcrumbs in bbg and quick tour

---

website/two-column-pages/docs/learn/quick-tour.md

fixed code block

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-guides.css

Fixed the BBG tabs

---

website/tools/guides/index.html

Update BBG index.html

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/docs/downloads.md
website/main-pages/mkdocs.yml

> For the latest download, release information will be fetched from the yaml file

Automating the download page - latest version

---

website/main-pages/ballerina.io-website-theme/css/blog-home-page.css

Update the new blog styles

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Adding line numbers to the ballerina code syntax highlighting

Adding line numbers to the ballerina code syntax highlighting

---

api-docs/docs/auth.authz.html
api-docs/docs/auth.authz.permissionstore.html
api-docs/docs/auth.basic.html
api-docs/docs/auth.jwtAuth.html
api-docs/docs/auth.userstore.html
api-docs/docs/caching.html
api-docs/docs/collections.html
api-docs/docs/data.sql.html
api-docs/docs/file.html
api-docs/docs/io.html
api-docs/docs/time.html
api-docs/docs/transactions.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/img/submit-button-icon.svg

Updated the new API Docs and submit button

---

playground-controller/pom.xml
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/autoscaler/IdleLauncherController.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/autoscaler/LauncherReplicationController.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/autoscaler/ReplicationController.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/autoscaler/util/ContainerRuntimeClient.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/autoscaler/util/KubernetesClientImpl.java
pom.xml

This PR adds the initial structure for the `playground-controller` module.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content …

Add initial playground-controller structure on autoscaler

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fixed the mobile menu

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/docs/philosophy.md

Updating the open source links table

Updating the open source links table

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fixed the menu height

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Fixing long code box issue

---

website/two-column-pages/docs/learn/quick-tour.md

Remove monaco editor and allow the default syntax highlighting.

Updating the quick start page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

Fixed the col width

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Change the font size to 16px

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

Fixed the headers

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs
website/main-pages/ballerina.io-website-theme/js/download/archived_download.js
website/main-pages/mkdocs.yml
website/tools/releases/generate_all_archived_json.py
website/tools/releases/release_note_md_to_html.py

Add release notes to archived releases page

Add release notes to archived releases page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-guides.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Fixed the top menu font

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/help-page.css

Fixed the tables and the home page font size

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/docs/downloads/archived.md

Add breadcrumb to Archived Versions page

Add breadcrumb to Archived Versions page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Fixed the fonts on philosophy page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/tools/ballerinaByExample/tools/generate.go

> Fix code block styling & download page archived link margin issue

Fix code block styling & download page archived link margin issue

---

website/tools/ballerinaByExample/tools/generate.go

Update BBE git base url

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/slack-page.css
website/two-column-pages/docs/open-source/slack.md

Style slack page

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Form submission will happen upon the submit button and the enter key press event

Added enter key submit event to the subscribe form

---

website/tools/ballerinaByExample/templates/example.tmpl

Fix bbe build

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/main-pages/ballerina.io-website-theme/samples/asynchronous-reliable-messaging.txt
website/main-pages/ballerina.io-website-theme/samples/connectors.txt
website/main-pages/ballerina.io-website-theme/samples/type-safe-endpoint-integration.txt
website/main-pages/docs/philosophy.md

Removing monaco from philosophy page and adding new one

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/guides/ballerina.io-guide-theme/base.html

Focus on search box when click on search icon

Focus on search box when click on search icon

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/ballerina.io-website-theme/js/philosophy.js

Fixing broken code box

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Update api docs styles

---

playground-controller/dependency-reduced-pom.xml
playground-controller/pom.xml
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/ControllerRunner.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/Main.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/ContainerRuntimeClient.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/model/Deployment.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/persistence/InMemoryPersistence.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/persistence/Persistence.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/scaling/LauncherClusterManager.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerService.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerServiceManager.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/util/Constants.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/util/ControllerUtils.java

Minor refactoring to Playground Controller scaler

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

> Fix styling issue on BBE output console in the code block along with some tweaks

Fix styling issue on BBE output console in the code block

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/ballerina.io-website-theme/js/download-page.js
website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

Update date format to "'MMM DD, Y" in download and archived releases pages

Update date format to "'MMM DD, Y" in download and archived releases pages

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

> Fix search results horizontal scroll issue
> Fix code highlighting issue in BBE output code block

Fix search results horizontal scroll issue

---

playground-controller/pom.xml
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/ContainerRuntimeClient.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/scaling/LauncherClusterManager.java
playground-controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerServiceManager.java
playground-widget/resources/docker/controller/Dockerfile
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml

Fix issue where the created objects were not immediately observed on the read APIs in K8S

---

website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

Remove latest release from archived releases

Remove latest release from archived releases

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/download-page.css

Font size fixes

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/ballerinaByExample/templates/example.tmpl

> Fix BBE code description ol listing UI issue
> Some style tweaks in search results

Fix BBE code description ol listing UI issue

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/ballerina.io-website-theme/js/download-page.js

Fixed the fonts and tables

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update footer links

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css

> Fix BBE next previous button height issue on content increase

Fix BBE next previous button height issue on content increase

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update date format

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Fix search box

---

website/main-pages/ballerina.io-website-theme/base.html
website/three-column-pages/three-column-pages/base.html
website/tools/ballerinaByExample/templates/example.tmpl
website/two-column-pages/ballerina.io-two-col-theme/base.html

Move search.js to bottom of the body

Move search.js to bottom of the body

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/img/download-bg-green-fill.svg
website/main-pages/ballerina.io-website-theme/img/toc-bg-circle.svg
website/main-pages/ballerina.io-website-theme/img/toc-bg.svg

Fixed the downloads page

---

website/main-pages/ballerina.io-website-theme/js/release_notes/all_release_notes.js

Removed edit on github from release notes page.

Removed edit on github from release notes page

---

website/tools/releases/release_note_md_to_html.py

Update release_note_md_to_html.py script

Update release_note_md_to_html.py script

---

website/main-pages/ballerina.io-website-theme/js/download/archived_download.js
website/main-pages/ballerina.io-website-theme/js/release_notes/all_release_notes.js

Update sorting in releases

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/tools/guides/ballerina.io-guide-theme/base.html

Fix layout issues

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/three-column-pages/mkdocs.yml
website/tools/ballerinaByExample/templates/example.tmpl
website/two-column-pages/mkdocs.yml

> Update BBE favicon
> Fix Release notes styling
> Remove Archived page config from two column layout

Fix Release notes styling + Update BBE favicon

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

Updated the api style

---

.gitignore
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/ControllerRunner.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/scaling/LauncherClusterManager.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerService.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/util/Constants.java
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/controller/controller-service.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/deploy-all-controllers.sh
playground-widget/resources/k8s/deploy-validator.sh
playground-widget/resources/k8s/undeploy-all-controllers.sh
playground-widget/resources/k8s/undeploy-validator.sh

Fix minor issues in clustering and AS logic

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/download-page.js
website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js

> Fix code-box consistent style issues
> Fix SHA-1 line wrap issue in download page

 Fix code-box consistent style issues

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

New categories for the BBE were added with a URL value for each example

Updated the BBE with the new categorization

---

website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

Removed latest release from archived downloads

Removed latest release from archived downloads

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/js/download-page.js

> Update download page downloads arrow icon location

Update download page downloads arrow icon location

---

website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs

> Add updated download page styling to archived page

Add updated download page styling to archived page

---

website/main-pages/docs/downloads.md

Wrapped the nightly build container in a new div to hide when the nightly builds are empty

Empty nightly build validation

---

website/main-pages/ballerina.io-website-theme/js/Philosophy - Ballerina.io.html
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update email place holder

---

website/main-pages/ballerina.io-website-theme/js/Philosophy - Ballerina.io.html
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update email placeholder to "I consent to join the email list"

Update email placeholder to "I consent to join the email list"

---

playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/ControllerRunner.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/ContainerRuntimeClient.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/persistence/Persistence.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/scaling/LauncherClusterManager.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerService.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerServiceManager.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/util/Constants.java
playground-widget/resources/k8s/cache_responder/cache-responder-deployment.yaml
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/watcher/watcher-deployment.yaml

Add more refactoring for code readability and role separation in Controller

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/two-column-pages/docs/open-source.md

Added 18px font size to the tagline

Made the theme font larger to 18px

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

Fixed camel case and removed redundant words under a given title

Added text fixes to BBE titles

---

website/tools/ballerinaByExample/templates/index.tmpl
website/tools/guides/index.html

Fixed title text has wrong capitalization

Fixed the page title with right capitalization

---

website/main-pages/ballerina.io-website-theme/js/download-page.js

>Nightly build placeholder will be hidden when the JSON response is empty

Nightly build empty JSON response handled

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/docs/philosophy.md

Updated the Design Principles on philosophy page

---

website/tools/ballerinaByExample/tools/generate.go

Skip invalid BBEs while building.
Extracted segmentation to a new function.
Used defer and recovery methods to handle panics in go code

Skip invalid BBEs while building.

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

> Each category should be displayed in a pre-defined column according to the new order. Added a new parameter to the JSON dataset to define the column id

Updated the BBE structure

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Fixed api docs styles

---

playground-widget/apis/controller/pom.xml
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/scaling/LauncherClusterManager.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/util/Constants.java
playground-widget/apis/utils/src/main/java/org/ballerinalang/platform/playground/utils/model/LauncherRequest.java
playground-widget/resources/docker/controller/Dockerfile
playground-widget/resources/docker/controller/build-image.sh
playground-widget/resources/docker/controller/netty-transports.yml
playground-widget/resources/docker/launcher/Dockerfile
playground-widget/resources/docker/launcher/build.sh
playground-widget/resources/docker/launcher/netty-transports.yml
playground-widget/resources/k8s/cache_responder/cache-responder-service.yaml
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/controller/controller-service.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/launcher/launcher-deployment.yaml
playground-widget/resources/k8s/launcher/launcher-service.yaml
playground-widget/resources/k8s/parser/parser-service.yaml
playground-widget/resources/k8s/redis/redis-master-service.yaml
playground-widget/resources/k8s/redis/redis-slave-service.yaml
playground-widget/resources/k8s/watcher/watcher-deployment.yaml

Adjust scale down  logic

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js

> Fix description boxes overlapping issue in philosophy page
> Reduce font size of download button signature files
> Fix philosophy page code box section height not resizing issue

Fix description boxes overlapping issue in philosophy page

---

playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/util/Constants.java
playground-widget/apis/launcher/src/main/java/org/ballerinalang/platform/playground/launcher/core/util/LauncherUtils.java
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/launcher/launcher-deployment.yaml
playground-widget/resources/k8s/watcher/watcher-deployment.yaml

Improve AS launcher information collection and fix missing launcher ack header

---

website/main-pages/ballerina.io-website-theme/samples/asynchronous-execution-shell.txt
website/main-pages/ballerina.io-website-theme/samples/asynchronous-execution.txt
website/main-pages/ballerina.io-website-theme/samples/docker-and-kubernetes.txt
website/main-pages/ballerina.io-website-theme/samples/rest-services.txt
website/main-pages/docs/philosophy.md

> Update cloud native code samples in philosophy page

Update cloud native code samples in philosophy page

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

> Fix an padding issue in philosophy page right description box container

Fix an padding issue in philosophy page right description box container

---

playground-widget/web/src/components/navigation/SamplesList.css
playground-widget/web/src/samples/data.json

> Fix "Asynchronous" link typo in playground widget

Fix "Asynchronous" link typo in playground widget

---

playground-widget/resources/docker/parser/.dockerignore
playground-widget/resources/docker/parser/Dockerfile
playground-widget/resources/docker/parser/docker-entrypoint.sh
playground-widget/resources/docker/parser/pom.xml

Root cause was lack of some stblib jars in service classpath
while building the parse tree.

Fix parse tree generation for async & data-service samples

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Updated philosophy page tabel font

---

website/main-pages/docs/philosophy.md

> Remove lambda code block highlight description from philosophy page

Remove lambda code block highlight description from philosophy page

---

website/two-column-pages/mkdocs.yml

Add new pages under learn section

---

api-docs/docs/auth.html
api-docs/docs/builtin.html
api-docs/docs/caching.html
api-docs/docs/compression.html
api-docs/docs/config.html
api-docs/docs/file.html
api-docs/docs/grpc.html
api-docs/docs/http.html
api-docs/docs/index.html
api-docs/docs/internal.html
api-docs/docs/io.html
api-docs/docs/jwt.html
api-docs/docs/log.html
api-docs/docs/math.html
api-docs/docs/mime.html
api-docs/docs/observe.html
api-docs/docs/os.html
api-docs/docs/primitive-types.html
api-docs/docs/reflect.html
api-docs/docs/runtime.html
api-docs/docs/security.crypto.html
api-docs/docs/sql.html
api-docs/docs/swagger.html
api-docs/docs/task.html
api-docs/docs/time.html
api-docs/docs/transactions.html
api-docs/docs/user.html
api-docs/docs/util.html

Latest api docs

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/js/download-page.js
website/main-pages/mkdocs.yml

> Nightly packs will be hosted at /nightly. Updated the download page accordingly.

Nightly build pack locations updated

---

api-docs/docs/auth.html
api-docs/docs/builtin.html
api-docs/docs/caching.html
api-docs/docs/compression.html
api-docs/docs/config.html
api-docs/docs/file.html
api-docs/docs/grpc.html
api-docs/docs/http.html
api-docs/docs/index.html
api-docs/docs/internal.html
api-docs/docs/io.html
api-docs/docs/jwt.html
api-docs/docs/log.html
api-docs/docs/math.html
api-docs/docs/mime.html
api-docs/docs/observe.html
api-docs/docs/os.html
api-docs/docs/primitive-types.html
api-docs/docs/reflect.html
api-docs/docs/runtime.html
api-docs/docs/security.crypto.html
api-docs/docs/sql.html
api-docs/docs/swagger.html
api-docs/docs/task.html
api-docs/docs/time.html
api-docs/docs/transactions.html
api-docs/docs/user.html
api-docs/docs/util.html

Updated api docs

---

website/main-pages/ballerina.io-website-theme/css/help-page.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

 Fixed the table headers

---

playground-widget/resources/k8s/cache_responder/cache-responder-deployment.yaml

Add missing NFS volume to cache responder

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/two-column-pages/docs/privacy-policy.md

Seperate file for privacy policy

Added privacy-policy.md

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/docs/philosophy.md
website/three-column-pages/three-column-pages/base.html
website/two-column-pages/ballerina.io-two-col-theme/base.html

> Fix base templates mkdocs syntax issue
> Move ballerina syntax highlighting grammar to global from philosophy page
> Fix philosophy page responsive issues on small screens

Fix philosophy page responsive issues on small screens

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css

Fixed selected package name and fonts

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Update API docs column width and font weight

---

.gitmodules
website/main-pages/ballerina.io-website-theme/js/philosophy.js

> Four new BBG added to the guides repo and updated the BBG listing with the new categories.

Added new BBG and updated the categories

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/main-pages/docs/philosophy.md
website/tools/guides/index.html

> Applied this to the BBG landing page and the philosophy page

BBG placeholder updated to have two columns

---

website/tools/ballerinaByExample/tools/generate.go

generate a json file with successful BBE Ids

generate a json file with successful BBE Ids

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/templates/index.tmpl

> Add highlight js to BBE pages
> Add highlight js library loaded check to prevent code break

Add highlight js library loaded check to prevent code break

---

playground-widget/apis/controller/pom.xml
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/ControllerRunner.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/scaling/LauncherClusterManager.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerService.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/service/ControllerServiceManager.java
playground-widget/resources/docker/controller/init.sh
playground-widget/resources/docker/controller/log4j.properties
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/launcher/launcher-deployment.yaml
playground-widget/resources/k8s/watcher/watcher-deployment.yaml

Fix logging and update image tags

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

- Update content of how-to-extend-ballerina.md
- Remove unwanted dependencies. 
- Add missing code 
- Add more comments

Update content of how-to-extend-ballerina.md

---

website/two-column-pages/mkdocs.yml

Added correct link to privacy policy

Added privacy policy

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/tools/generate.go

> Remove default code syntax highlighting add ballerina language highlighting support to BBE pages

Add ballerina language highlighting support to BBE pages

---

website/main-pages/docs/philosophy.md

All section headers are on one line

Removed line wraps

---

website/tools/ballerinaByExample/tools/all-bbes.json
website/tools/ballerinaByExample/tools/generate.go

Read example list from pre formatted json file(which is based on BBE categories) instead of example.txt

Read example list from pre formatted json file

---

README.md

> Update README with git sub module update command

Update README with git sub module update command

---

api-docs/docs/ballerina/auth.html
api-docs/docs/ballerina/builtin.html
api-docs/docs/ballerina/caching.html
api-docs/docs/ballerina/compression.html
api-docs/docs/ballerina/config.html
api-docs/docs/ballerina/file.html
api-docs/docs/ballerina/grpc.html
api-docs/docs/ballerina/http.html
api-docs/docs/ballerina/internal.html
api-docs/docs/ballerina/io.html
api-docs/docs/ballerina/jwt.html
api-docs/docs/ballerina/log.html
api-docs/docs/ballerina/math.html
api-docs/docs/ballerina/mime.html
api-docs/docs/ballerina/observe.html
api-docs/docs/ballerina/os.html
api-docs/docs/ballerina/primitive-types.html
api-docs/docs/ballerina/reflect.html
api-docs/docs/ballerina/runtime.html
api-docs/docs/ballerina/security.crypto.html
api-docs/docs/ballerina/sql.html
api-docs/docs/ballerina/swagger.html
api-docs/docs/ballerina/time.html
api-docs/docs/ballerina/transactions.html
api-docs/docs/ballerina/user.html
api-docs/docs/ballerina/util.html

 Update api docs

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Fix hover effect on links

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

> Reduce H2 & its bottom border gap

Reduce H2 & its bottom border gap

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

Added in links to these repositories.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …

Docker + k8s links to custom annotations

---

website/tools/api-docs/templates/index.hbs
website/tools/api-docs/templates/package-list.hbs
website/tools/api-docs/templates/page.hbs

Add docerina templates specific to io site

---

website/tools/api-docs/templates/page.hbs

Remove package list content

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

- Update builder extension info with new dependencies

Update builder extension info with new dependencies

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/api-docs/templates/page.hbs

> Fix API docs code highlighting not working issue

Fix API docs code highlighting not working issue

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/main-pages/docs/philosophy.md
website/tools/ballerinaByExample/templates/index.tmpl

> Reading the BBE entries from the main JSON and validating it with the generated BBE json and displaying only the generated BBEs in the page

Removing non-generated BBEs from the main listing

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css

> Add margin top to release notes version title
> Fix download button padding issue

Download page style fixes

---

api-docs/docs/ballerinax/primitive-types.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Fix api docs styles

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/ballerina.io-website-theme/js/release_notes/all_release_notes.js

> Add code ballerina code highlighting support to release notes

Add code ballerina code highlighting support to release notes

---

website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

> Add ballerina code highlighting to archived downloads release notes

Add ballerina code highlighting support to archived downloads release notes

---

website/tools/api-docs/templates/page.hbs

Add summary tables

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css

Fix BBE Mobile view

---

website/tools/api-docs/templates/page.hbs

Fix template

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

Update gmail-spreadsheet-integration name

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Fixed API docs summury table

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Restructured the headings so that more of the major topics will appear in the TOC generator.

Restructure to get entries into TOC

---

website/tools/api-docs/templates/page.hbs

Improve template

---

website/tools/api-docs/templates/page.hbs

Added subsection headers

---

website/tools/api-docs/templates/page.hbs

Improved summary view

---

website/main-pages/ballerina.io-website-theme/base.html
website/three-column-pages/three-column-pages/base.html
website/tools/api-docs/templates/index.hbs
website/tools/api-docs/templates/page.hbs
website/tools/ballerinaByExample/templates/index.tmpl
website/tools/guides/ballerina.io-guide-theme/base.html
website/tools/guides/index.html
website/two-column-pages/ballerina.io-two-col-theme/base.html

> Remove default highlight.css file from templates

Remove default highlight.css file from templates

---

website/two-column-pages/docs/learn.md
website/two-column-pages/docs/open-source/slack.md

> API-docs URL is updated to point to the latest redirection
> Text box place holder updated

API-docs URL and text box updates

---

website/main-pages/docs/philosophy.md
website/tools/api-docs/templates/page.hbs

Added 
Ballerina is a general purpose, concurrent, transactional and statically & strongly typed programming language with both textual and graphical syntaxes. Its specialization is integration - it brings fundamental concepts, ideas and tools of distributed system integration into the language and offers a type safe, concurrent environment to implement such applications. These include distributed transactions, reliable messaging, stream processing, workflows and container management platforms.

Added new para by Sanjiva on the language

---

website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js

> Fix example contents "some code lines are missing" issue

Fix example contents "some code lines are missing" issue

---

pom.xml
website/pom.xml
website/tools/ballerinaByExample/tools/generate.go

Add support for multiple bal files. Update dir paths and file paths of BBEs

Add support for multiple bal files

---

website/main-pages/docs/philosophy.md

> Fix periods in philosophy page code comments

Fix periods in philosophy page code comments

---

website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js
website/main-pages/ballerina.io-website-theme/samples/logic-language-shell.txt
website/main-pages/docs/philosophy.md

> Fix output code not showing properly issue on philosophy page

Fix output code not showing properly issue on philosophy page

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Fix ballerina type keywords highlights in non keyword words

Fix ballerina type keywords highlights in non keyword words

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Adding padding to the code block on the What are Ballerina's language principles section

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/samples/protection-against-injection-attacks.txt
website/main-pages/docs/philosophy.md

> Fix footer sign-up controller padding issue
> Fix protection-against-injection-attacks sample last line readability issue

Fix footer sign-up controller padding issue + An issue in philosophy page

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Reducing the padding height of the code box

Reducing the padding height

---

website/tools/api-docs/templates/page.hbs

Load package list

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/samples/type-system.txt

> Improve type system code block styling in philosophy page

 Improve type system code block styling in philosophy page

---

playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/containercluster/KubernetesClientImpl.java
playground-widget/apis/controller/src/main/java/org/ballerinalang/platform/playground/controller/util/Constants.java
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/watcher/watcher-deployment.yaml
playground-widget/web/src/samples/data.json

Also includes a minor fix to backend optimizations

Rename external service sample & update samples with latest changes

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

and removed second para thanking tools used

Added Elm to footer thank you text 

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Form messages are shown in the placeholder of the textbox

Confirmation message placeholder removed

---

pom.xml
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/tools/all-bbes.json
website/tools/ballerinaByExample/tools/generate.go

Update BBEs for 0.970.0-beta16

Update BBEs for 0.970.0-beta16

---

website/two-column-pages/docs/learn/quick-tour.md

WiP: Update quick-tour.md

---

pom.xml

Update BBE to beta17

---

website/tools/ballerinaByExample/tools/all-bbes.json

Update BBE Names

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js
website/main-pages/docs/philosophy.md

> Fix highlight.js regex error
> Do sample code blocks related tweaks on philosophy page

Philosophy page style tweaks & highlight.js broken fix

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Update how-to-write-secure code document with:
* Reviewed content relevant to taint-checking
* New content relevant to security passwords and secrets

 Update how-to-write-secure code document

---

website/two-column-pages/docs/learn/faq.md

WiP: Create faq.md

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Fix minor typos

---

website/tools/api-docs/templates/page.hbs

Move global vars and types down

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Add missing function for #608
> #608

Add missing function for #608

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css

Update BBE border shadows

---

website/main-pages/ballerina.io-website-theme/samples/circuit-breaker.txt
website/main-pages/ballerina.io-website-theme/samples/protection-against-injection-attacks.txt
website/main-pages/ballerina.io-website-theme/samples/reliable-messaging.txt
website/main-pages/docs/philosophy.md

> Update integration framework samples section content

Update integration framework samples section content

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-guides.css

Update guides copy url width

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/docs/philosophy.md

> Stop word wrapping of search result headings
> Lowercase "open source" title in philosophy page

Stop word wrapping of search result headings

---

website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md

Fix some sentences.
Fix styling issues. 
Format markup code. Removed spaces.
Tested website.

Update observability learn page. 

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Update ballerina language syntax keywords

Update ballerina language syntax keywords

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Add "match & but" keywords to updated ballerina language syntax highlighting

Add "match & but" keywords to updated ballerina language syntax highlighting

---

website/tools/api-docs/templates/page.hbs

Fixed function table

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/tools/search/search.js

> Style "No results found" text in search results window

Style "No results found" text in search results window

---

website/tools/api-docs/templates/page.hbs

Fix cross links for union/tuple

---

website/two-column-pages/docs/learn/quick-tour.md

Some minor technical details were changed.

Fix some minor issues

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

change string[] to string... in the main function

change string[] to string... in the main function

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api.css

Update API docs theme

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

* Correct conf file name used in sample.
* Few technical changes related to curl commands and code.

Correct conf file name used in sample

---

website/two-column-pages/docs/learn/quick-tour.md

Move IDE plugins link to 'Setup Editor' section

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/tools/ballerinaByExample/templates/example.tmpl

> Disable auto pick code highlighting for undefined languages
> Enable output code highlighting in BBE along with some style tweaks

BBE page code highlighting style tweaks

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Adding the search box small screen fix

---

pom.xml

Update BBE to RC1

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Remove empty space

---

website/pom.xml

Removing three columns execution and blog

Removing three columns execution and blog

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

> Fix BBE line number overflowing issue on yaml examples
> Fix search results box expands over the screen when have no white space texts

Fix BBE line number overflowing issue on yaml examples + Search results expands over screen issue

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Add Testerina Doc

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Fix menu not displaying issue

Fix menu not displaying issue

---

website/two-column-pages/docs/learn/quick-tour.md

This PR adds a description to the "composer" segment

Add a description to composer segment within quick tour

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/docs/index.md

> Add loader animation till home page playground widget loads + Add a fix width to search results window

Add loader animation till home page playground widget loads + Add a fix width to search results window

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/tools/ballerinaByExample/templates/example.tmpl

Fixed BBE for safari

---

pom.xml
website/tools/ballerinaByExample/tools/all-bbes.json

Update BBE to 0.970.0

---

website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs
website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

Add idea plugin to archived releases page

Add idea plugin to archived releases page

---

website/tools/search/search.js

> Search will start after typing two characters
> Search function will be called after one second delay (to allow the user to type the phrase)

Search rules updated

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Adding search fix for mobile view

Adding search fix for mobile view

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fixing mobile display of the search box

---

website/tools/ballerinaByExample/tools/all-bbes.json

Update BBE category ordering

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/download-page.css

Fixed the announcement list

---

website/main-pages/ballerina.io-website-theme/navigation.html

Remove Con banner

---

website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs
website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

Update download links of idea plugin
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Update download links of idea plugin

---

website/two-column-pages/docs/learn.md
website/two-column-pages/mkdocs.yml

> pdf will be downloaded upon the link click

Removed language specification page

---

website/two-column-pages/docs/learn.md

Add more articles from across the team.

Add articles.

---

website/main-pages/ballerina.io-website-theme/js/download-page.js
website/main-pages/docs/downloads.md

> Data layer variables will hold the pack name and will push the value as the label for tag manager tracking

Added data layer attributes for tracking purposes

---

website/two-column-pages/docs/learn/faq.md
website/two-column-pages/docs/learn/how-to-extend-ballerina.md

Broken URL fixed

---

website/two-column-pages/docs/learn/how-to-document-ballerina-code.md

Add review changes

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Update Testing Doc

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Removed the banner styles from the main css

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

Fix Type "password":
- db-passowrd -> db-password
- key-store-passowrd -> key-store-password
- trust-store-passowrd -> trust-store-password
> Brief description of the new feature or bug fix as it will appear in the …

Fix Typo "password"

---

website/main-pages/ballerina.io-website-theme/base.html

Update twitter image path

---

website/two-column-pages/docs/open-source.md

Rewording schwag to stuff in open-source.md

---

website/main-pages/docs/philosophy.md

Fixed typo in philosophy.md

---

website/two-column-pages/docs/learn/quick-tour.md

Fix Quick Tour file

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/two-column-pages/ballerina.io-two-col-theme/base.html

> Remove philosophy page code box padding on mobile view
> Move menu active state highlight method to common script
> Fix mobile view navigation menu font styling

Navigation style fixes + Philosophy page mobile view fixes

---

website/two-column-pages/docs/security.md

Update pgp key and link

---

website/two-column-pages/docs/learn/faq.md

This PR contains language and formatting improvements. 
None
Please double check the whole FAQ page look and feel when you deploy to prod.

Adding improvements to the FAQ both text and formatting

---

website/main-pages/docs/philosophy.md

> Update philosophy page code block line highlighting for changes in PR #760
> #760
> Please merge #760 along with this PR

Update philosophy page code block line highlighting for changes in PR #760

---

website/main-pages/ballerina.io-website-theme/samples/distributed-transactions.txt
website/main-pages/ballerina.io-website-theme/samples/docker-and-kubernetes.txt
website/main-pages/ballerina.io-website-theme/samples/protection-against-injection-attacks.txt
website/main-pages/ballerina.io-website-theme/samples/type-safe-connectors.txt

Fix syntax changes in the examples
None
Need to fix the philosophy.md

Fix syntax changes in the examples

---

website/two-column-pages/docs/learn/quick-tour.md

Formatting fix in quick-tour.md

---

website/two-column-pages/docs/security.md

Fix https://github.com/ballerina-platform/ballerina-www/issues/786

Added links to email

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/docs/philosophy.md

> Fix philosophy page code description paragraph spacing to match container padding
> Fix download page "build instructions" link text weight
> N/A
> N/A

Some text style fixes on philosophy & download pages

---

website/two-column-pages/docs/learn/faq.md

Removed duplicate sentence and updated the value prop

Update the FAQ

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

> Add default styling for <dt> elements
> N/A
> N/A

Add default styling for <dt> elements

---

website/main-pages/docs/philosophy.md

Removed the open source section form philosophy page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

 Update philosophy-page layout

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Update philosophy-page layout

---

website/pom.xml
website/tools/build-philosophy-samples.sh

Add script to build language features samples in philosophy page during the build.

Add script to build language feature samples in philosophy page during the build

---

website/main-pages/build.sh
website/three-column-pages/build.sh
website/tools/ballerinaByExample/tools/generate.go
website/tools/guides/build.sh
website/two-column-pages/build.sh

> [Fix #807] Files not copying issue when build on windows
> N/A
> Tested on Windows 10 & Mac

[Fix #807] Files not copying issue when build on windows

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js
website/main-pages/docs/philosophy.md
website/tools/guides/build.sh

> Add copy to clipboard option to philosophy page code samples (Related to issue: #742)
> N/A
> N/A

 Add copy to clipboard option to philosophy page code samples

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css

Fix the philosophy page text boxes

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fixed the copy button alignment

---

website/two-column-pages/docs/learn/quick-tour.md

Fixed quick tour guide by adding missing Docker annotations.

Fixed quick tour guide by adding missing Docker annotations.

---

website/tools/api-docs/templates/page.hbs

Add package name to the page title

---

website/main-pages/ballerina.io-website-theme/samples/type-system.bal

> Fixing the missing type-system code in the philosophy page
>
> Check the design principles - type system tab to verify this change

Adding type system code to the philosophy page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/ballerina.io-website-theme/js/philosophy-syntax.js

> [Fix #742] Prevent numbers copying when code segment copying in philosophy page
> #814
> N/A

[Fix #742] Prevent numbers copying when code segment copying in philosophy page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs

> [Fix #775] Spacing issue in downloads archived page release notes
> N/A
> N/A

[Fix #775] Spacing issue in downloads archived page release notes

---

website/two-column-pages/docs/learn.md
website/two-column-pages/docs/learn/publish-package.md

Add ballerina push doc. Has info on Settings.toml file

Add ballerina push doc

---

website/two-column-pages/docs/learn.md
website/two-column-pages/docs/learn/how-to-publish-package.md

Add sub headings to ballerina push doc

Add sub headings to ballerina push doc

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/hbs/archived_list.hbs
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/docs/downloads.md

> Fix "TypeScript", "JavaScript" typo in the footer
> Fix archived download release notes styles conflict with page sub-heading style
> N/A
> N/A

Fix footer text typo + Release notes H3 style conflict

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/css/download-page.css

> Fix all nav links color changes to active on download pages
> N/A
> N/A

Fix all nav links color changes to active on download pages

---

website/main-pages/docs/page-not-found.md
website/main-pages/mkdocs.yml

Update 404 page

---

pom.xml

> Updated BBE version to 0.970.1
> -
> -

Updated BBE version

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fix the mobile menu url colour

---

website/two-column-pages/docs/learn/quick-tour.md

> fixed the twitter.toml config code highlighter
> -
> -

Fixde config code block

---

website/main-pages/ballerina.io-website-theme/css/download-page.css

Fix download page menu link colour

---

website/two-column-pages/docs/learn/quick-tour.md

Reverts ballerina-platform/ballerina-www#853

Revert "Update quick-tour.md"

---

website/two-column-pages/docs/learn/quick-tour.md

Reverts ballerina-platform/ballerina-www#852
The reviews need to be incoporated

Revert "Added the What you think section into the quick tour."

---

website/two-column-pages/docs/learn/quick-tour.md

Update git star container

---

website/two-column-pages/ballerina.io-two-col-theme/base.html

Update git star script

---

website/two-column-pages/docs/learn/quick-tour.md

Update the git star container

---

website/two-column-pages/docs/learn/getting-started.md

> Fixed default installation path in "Installing on Windows" section

[Getting Started] Content update: "Installing on Windows" section

---

website/main-pages/ballerina.io-website-theme/css/philosophy-page.css
website/main-pages/docs/philosophy.md

> Fix Responsive issue in philosophy page "Why did we build ballerina?" section

[Fix #870] Responsive issue in philosophy page "Why did ...?" section

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-blog-inner-pages.css
website/main-pages/ballerina.io-website-theme/css/blog-home-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update blog link

---

website/tools/ballerinaByExample/templates/example.tmpl

Fix BBE meta titles

---

.gitmodules
website/main-pages/ballerina.io-website-theme/js/philosophy.js

> Running with Istio guide added and updated the BBG listing
> -
>

BBG updated with Istio guide

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/navigation.html

Remove con banner animation

---

website/main-pages/docs/downloads.md

> Linked the installation instructions (https://ballerina.io/learn/getting-started/#installing-ballerina) from the main Download page

Linked the installation instructions

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

> Improving grammar and other aspects.
> None.

Update - how-to-test-ballerina-code.md

---

website/two-column-pages/docs/learn/quick-tour.md

Update quick-tour markdown

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Update how to test ballerina content

Update how to test ballerina content

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Fix testerina doc issues

---

website/two-column-pages/docs/learn/quick-tour.md

> Link "https://curl.haxx.se/download.html" in the "Start a Project ..."  section

Linked curl download page URL 

---

website/two-column-pages/docs/learn.md

Update ballerinacon url

---

website/two-column-pages/docs/learn.md

Update event url

---

website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/docs/learn.md

Fix the css caching issue

---

website/two-column-pages/docs/learn/how-to-document-ballerina-code.md

Update ballerina doc related document

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md
website/two-column-pages/docs/learn/quick-tour.md

- Update how-to-deploy-and-run-ballerina-programs guide
- Update docker for windows instructions

Update how-to-deploy-and-run-ballerina-programs guide

---

website/tools/ballerinaByExample/tools/all-bbes.json

> Three new BBEs added
> -
> -

New BBEs added for the 0.975.0 release

---

api-docs/docs/ballerina/auth.html
api-docs/docs/ballerina/crypto.html
api-docs/docs/ballerina/file.html
api-docs/docs/ballerina/h2.html
api-docs/docs/ballerina/http.html
api-docs/docs/ballerina/internal.html
api-docs/docs/ballerina/io.html
api-docs/docs/ballerina/jdbc.html
api-docs/docs/ballerina/mime.html
api-docs/docs/ballerina/reflect.html
api-docs/docs/ballerina/sql.html
api-docs/docs/ballerina/system.html
api-docs/docs/ballerina/task.html
api-docs/docs/ballerina/time.html
api-docs/docs/ballerina/websub.html

Update API docs 0.975.0

---

website/two-column-pages/docs/learn.md

Update events on learn page

---

website/main-pages/ballerina.io-website-theme/css/events-page.css
website/main-pages/ballerina.io-website-theme/css/webinar-page.css
website/two-column-pages/docs/learn.md
website/two-column-pages/docs/learn/events.md
website/two-column-pages/docs/learn/events/webinars.md
website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

Update new webinar

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

Update form validation styles

---

website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

> Jquery form validate library added to the base.html in the two-column pages
> 
>

Added validate library to the theme

---

website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

Update webinar info

---

website/two-column-pages/ballerina.io-two-col-theme/base.html

Update two col base

---

website/two-column-pages/docs/learn/getting-started.md

Changed ballerina installation path in "UNINSTALLING BALLERINA" section of the page [1].
[1] - https://stage.ballerina.io/learn/getting-started/#uninstalling-ballerina

changed the ballerina installation directory path in Linux

---

website/main-pages/ballerina.io-website-theme/js/jquery.validate.js

> Adding the Jquery validate library
> #930 
> -

Adding the Jquery validate library

---

website/main-pages/ballerina.io-website-theme/js/jquery.validate.js
website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

 Update the form

---

website/two-column-pages/ballerina.io-two-col-theme/base.html

Fix meta tags

---

website/main-pages/ballerina.io-website-theme/css/webinar-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

Fix the webinar page

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js

> Updated webinar registration status message
> 
> -

Updated webinar registration status message

---

website/two-column-pages/ballerina.io-two-col-theme/base.html

Update meta data

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/two-column-pages/docs/community-program.md
website/two-column-pages/mkdocs.yml

Add Community-program page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/two-column-pages/docs/community-program.md

Update community-program page

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/community-program.md

> Form and the logic added to store community program submissions
> #944 
>

Community program form functionality added

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/community-program.md

> Pardot endpoint updated. Form submit button value and the opt-in statement updated.
> -
> -

Updated Pardot resources and form

---

website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/docs/community-program.md

Update community page content

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css

Update text area styles

---

website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

> Updated opt-in field text
> -
> -

Updated opt-in field text

---

website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

Update register buttton id

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/main-pages/ballerina.io-website-theme/scripts/formSubmit.php

> Added AJAX based form submission
>
> -

Updated the community form submission

---

website/main-pages/ballerina.io-website-theme/scripts/formSubmit.php

> URL encode added to the form submission request
> -
> -

URL encode added to the form submission request

---

website/two-column-pages/docs/learn/events/webinars/ballerina-serverless-with-kubeless.md

> JS library cached version cleared
> -
> -

JS library cached version cleared

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

- Update Builder Extensions guide with new syntaxes and instructions

Update Builder Extensions guide

---

website/two-column-pages/docs/community-program.md

Fixes https://github.com/ballerina-platform/ballerina-www/issues/964

Correct post call in community engagement sample

---

website/tools/build-bbe.sh

> BBE build script is updated to clone the examples from the release branch instead of the master 
> -
> -

BBE build from the branch

---

website/main-pages/ballerina.io-website-theme/css/events-page.css
website/main-pages/ballerina.io-website-theme/js/events.js
website/two-column-pages/docs/learn/events.md

 Update events page

---

website/two-column-pages/docs/community-program.md

> This PR will update the package summary of the Package.md provided in community-program to have less than 50 characters
Fixes  https://github.com/ballerina-platform/ballerina-www/issues/971

Update package summary of the Package.md provided in community-program to have less than 50 characters

---

api-docs/docs/ballerina/docerina-theme/css/ballerina-common.js
api-docs/docs/ballerina/docerina-theme/js/ballerina-common.js
api-docs/docs/ballerinax/docerina-theme/css/ballerina-common.js
api-docs/docs/ballerinax/docerina-theme/js/ballerina-common.js
website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/docs/help.md

We have renamed the Twitter handle - need to update the site

Change ballerinaplat to ballerinalang

---

website/main-pages/ballerina.io-website-theme/js/download-page.js

> Updated the dev release json file location
> -
> -

Updated the dev release json file location

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

> Fixed most of the issues in running the guide

Fix "How to Extend Ballerina" guide

---

website/two-column-pages/docs/community-program.md

> Fixes https://github.com/ballerina-platform/ballerina-www/issues/984
> Fixes https://github.com/ballerina-platform/ballerina-www/issues/981
> Fixes https://github.com/ballerina-platform/ballerina-www/issues/980
> Fixes https://github.com/ballerina-platform/ballerina-www/issues/963

Fix compile errors for 0.980.0

---

website/two-column-pages/docs/learn/quick-tour.md

> Improve the quick tour guide
> Fix #884

Update quick tour guide

---

website/main-pages/docs/downloads.md

> Removed RC download section
> -
> -

Removed RC download section

---

playground-widget/pom.xml
playground-widget/resources/k8s/controller/controller-deployment.yaml
playground-widget/resources/k8s/cron_jobs/desiredcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/maxcheck-cron.yaml
playground-widget/resources/k8s/cron_jobs/validator-cron.yaml
playground-widget/resources/k8s/launcher/launcher-deployment.yaml
playground-widget/resources/k8s/parser/parser-deployment.yaml
playground-widget/web/src/components/console/Console.js
pom.xml

Migrate Playground to 0.980.0

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/docs/community-program.md

> Update community program page form styling and added github star/watch buttons above the form

Update community program page form

---

website/two-column-pages/docs/learn/tools-ides-ballerina-composer.md

Fix tools IDEs pages

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Remove start/stop services utility for the moment

---

website/main-pages/mkdocs.yml

> BBG and the yml updated for the 0.980.0 release
> -
> -

0.980.0 release artifacts added

---

website/two-column-pages/docs/learn/ballerina-streaming-reference.md

Change examples to comply with latest grammar (0.980.0)

---

website/two-column-pages/docs/learn/quick-tour.md

Update Git star link

---

.gitmodules
website/main-pages/ballerina.io-website-theme/js/philosophy.js

> Following guides added to the site
Content-based Routing
Passthrough messaging
Message filtering: https
Scatter gather messaging
> -
> -

New BBGs added to the site

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/two-column-pages/docs/open-source.md

> Updated Git Star and Watch buttons
> -
> -

Updated BBG names and Git Star buttons

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update ballerina day form

---

website/main-pages/ballerina.io-website-theme/css/ballerina-day.css
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update ballerina day page content

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

To fix this issue: https://twitter.com/chj915/status/1019993806710554624/photo/1

Add extra line after "repositories" to fix list formatting

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update radio buttons

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

> Two new fields added to the form
> #1053 
> -

Ballerina day form updated with new fields

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

> Updated validation of the Ballerina day form
> #1057 
> -

Updated validation of the Ballerina day form

---

website/two-column-pages/docs/learn/events.md
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update the events page and ballerina day page

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

> Updated confirmation message
> #1058 
> -

Updated confirmation message

---

website/two-column-pages/docs/learn/events/webinars/continuous-delivery-for-cloud-native-applications-with-kubernetes-ballerina-and-codefresh.md

> updated webinar ID and pardot endpoint
> -
>-

updated webinar ID and pardot endpoint

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update content and removed the country field

---

website/two-column-pages/docs/learn/events.md

Update events page

---

website/two-column-pages/docs/learn/events.md

> Updated webinar registration button text
> -
> -

Updated webinar registration button text

---

website/two-column-pages/docs/learn/events/webinars/container-native-log-processing-with-ballerina-and-humio.md

Fixed sm image

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Add line breaks after 80 characters in code segments, to prevent readers having to scroll in order to read the full code. 
N/A
N/A

Add line breaks at 80 chars to code blocks

---

website/two-column-pages/docs/learn/getting-started.md

> Fix [1] and [2].
[1] https://github.com/ballerina-platform/ballerina-www/issues/869
[2] https://github.com/ballerina-platform/ballerina-lang/issues/7321

Updated getting-started.md

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

- Fix k8s annotation samples
- Resolves https://github.com/ballerina-platform/ballerina-www/issues/1065

Fix k8s annotation sample

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Add line break in run command to avoid having to scroll to see the full command
N/A
N/A

Add line break in run command

---

website/main-pages/ballerina.io-website-theme/css/ballerinacon-page.css

Update ballerina con session page styles

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

> Fixed the company and the job title field names in the form
> -
> -

Fixed the field names in the form

---

website/two-column-pages/docs/community-program.md

- Reformat the community program markdown to improve code redability.
- Please note that this does not have any functional changes.

Reformat community program markdown

---

website/two-column-pages/docs/community-program.md

Fixes https://github.com/ballerina-platform/ballerina-www/issues/1069

Fix for invalid choice rejection of calculator

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update ballerina day dates

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/microservice-Integration-and-ballerina.md

BalCon Update microservice-Integration-and-ballerina.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/service-resiliency-in-microservices.md

> Update SlideShare download button.

BalCon Update service-resiliency-in-microservices.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/cloud-native-programing-with-docker-and-kubernetes.md

> Update SlideShare download button with link.

BalCon Update cloud-native-programing-with-docker-and-kubernetes.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/service-mesh-in-practice.md

BalCon Update service-mesh-in-practice.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/test-driven-development-for-microservices.md

BalCon Update test-driven-development-for-microservices.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/serverless-ballerina.md

BalCon Update serverless-ballerina.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/observability-with-ballerina.md

BalCon Update observability-with-ballerina.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/ballerina-development-lifecycle-and-tools.md

> Remove download slides button.

BalCon Update ballerina-development-lifecycle-and-tools.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/secure-by-design-microservices-and-integrations.md

>Update SlideShare button with link.

BalCon Update secure-by-design-microservices-and-integrations.md

---

website/two-column-pages/docs/learn/events/ballerinacon-san-francisco-2018/stream-processing-with-ballerina.md

BalCon Update stream-processing-with-ballerina.md

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update ballerina day page

---

website/two-column-pages/docs/learn/events.md
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Events page update

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update session details

---

website/two-column-pages/ballerina.io-two-col-theme/base.html

Fix page meta title

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md
website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018/transport-confirmation.md
website/two-column-pages/mkdocs.yml

Update ballerina day form and confirmation pages

---

website/two-column-pages/docs/community-program.md

> Fix the outdated content in the community program doc

Fix community program doc issues

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

Fix broken links to Docker and Kubernetes

---

website/tools/ballerinaByExample/tools/all-bbes.json
website/tools/build-bbe.sh

> 4 New BBEs added with the release
> -
> -

New BBEs added for the 0.981.0 release

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

Update BBG categories

---

website/two-column-pages/docs/learn/events.md
website/two-column-pages/docs/learn/events/past-events.md
website/two-column-pages/docs/learn/events/webinars/continuous-delivery-for-cloud-native-applications-with-kubernetes-ballerina-and-codefresh.md

Updated codefresh webinar

---

website/tools/build-philosophy-samples.sh

> Fixed issue: Philosophy page code sample testing failure on windows.
> Added a OS check for windows. But please verify on linux

Fix #1144 - Philosophy page code sample test fail

---

website/two-column-pages/docs/learn/getting-started.md

Update Getting started page

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md
website/two-column-pages/docs/learn/quick-tour.md

Update learn content

---

website/main-pages/ballerina.io-website-theme/samples/best-practices.bal

Fix best practices sample

---

website/two-column-pages/docs/learn/getting-started.md

> Include correct installation locations

Include correct installation locations

---

website/two-column-pages/docs/learn/events/past-events.md

Update past events

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Fix ordered list

---

website/main-pages/ballerina.io-website-theme/samples/endpoints.bal

Change twitter configuration

---

website/two-column-pages/docs/learn/quick-tour.md

> Remove unnecessary download button part

Remove unnecessary download button part

---

website/two-column-pages/docs/learn/events.md

Update Brazil meetup

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/main-pages/docs/philosophy.md

> Update philosophy page content

Update philosophy page content

---

website/main-pages/docs/philosophy.md

> Fixed highlight issue in annotation example

Fix highlight issue in annotation example

---

website/main-pages/docs/philosophy.md

> Fixed comment in API security sample

Fix comment in API security sample

---

website/two-column-pages/docs/learn/how-to-document-ballerina-code.md

This PR updates the documentation with the new markdown documentation syntax.

Update to new markdown documentation syntax

---

website/main-pages/docs/philosophy.md
website/two-column-pages/docs/community.md

> Removed duplicate page content 
> Removed the broken repo link item
> -
> -

Fixed content repeating issue

---

api-docs/docs/ballerina/jdbc.html
api-docs/docs/ballerina/primitive-types.html

> This PR will fix minor typos in ballerina.io 
Fixes https://github.com/ballerina-platform/ballerina-www/issues/1111

Fix minor typos in ballerina.io

---

website/main-pages/ballerina.io-website-theme/samples/api-constructs.bal

I just checked your website and that space there bugged me.
No related PRs.
I don't know.
- Special styling concerns?
This PR is purely of stylistic nature...
- Related media files? 
No related media files.

Remove odd whitespace in api-constructs.bal

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

> Doc update to fix https://github.com/ballerina-platform/ballerina-www/issues/1149
> Removed the point that mentions about custom service listeners.
Checked with @jeradrutnam on getting the java syntax coloring for the java code segments towards the end of the doc. He will be fixing the syntax color for the java code segments.

Updated how-to-extend-ballerina.md

---

website/two-column-pages/docs/learn/quick-tour.md

I was going through the Quick Tour and found that the step by step instructions were inconsistent with both the example code at the end of the twitter example as well as the official wso2/twitter documentation examples: https://central.ballerina.io/wso2/twitter
I've made this update to make it more consistent and readable.

Make the twitter example consistent and easier to follow

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

This PR updates the how-to-structure-ballerina-code documentation, to reflect the changes to the `main` function.
https://github.com/ballerina-platform/ballerina-lang/pull/10060

Update how to structure Ballerina code for main function changes

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

> This PR will update how to structure ballerina code for changes in ballerina push, install and uninstall commands

Update how to structure ballerina code for changes in ballerina push, install and uninstall commands

---

website/two-column-pages/docs/learn/events.md

> Update Columbus Ballerina meetup event link to meetup.com

Update Columbus Ballerina meetup event link

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

Fix/Update run and deploy BBG

---

website/two-column-pages/docs/community-program.md

> This PR will update the community program quick tour.

Update community program

---

website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md

Purpose of this PR is to $subject.

Fix output logs in observability guide

---

website/two-column-pages/docs/learn/events.md
website/two-column-pages/docs/learn/events/past-events.md

> Moved past events from the events page to the past events page
> Added London meetup time, location and registration link
> -
> -

Updated meetup information and past events

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Rectify doc issues in "how to test your ballerina code" guide

Fix issues in how-to-test-ballerina-code.md

---

website/two-column-pages/docs/learn/tools-ides-ballerina-composer.md

> Change invalid composer guide content

Change invalid composer guide content

---

website/main-pages/ballerina.io-website-theme/samples/asynchronous.bal
website/main-pages/ballerina.io-website-theme/samples/idiomatic.bal
website/main-pages/ballerina.io-website-theme/samples/json-and-xml.bal
website/main-pages/ballerina.io-website-theme/samples/streams.bal
website/main-pages/ballerina.io-website-theme/samples/taint-analysis.bal
website/main-pages/ballerina.io-website-theme/samples/transactions.bal
website/main-pages/ballerina.io-website-theme/samples/workers.bal

> With this update the main function syntax

Update main function syntax

---

website/two-column-pages/docs/learn/quick-tour.md

This PR will update the code inside quick-tour with the doc comment changes from `ballerina init`

Update quick-tour with new generated code changes.

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

> Fix syntax issue in secure service guide

Fix syntax issue in secure service guide

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js
website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

> Ballerina Day form updated for the London event
> Updated Pardot campaigns and the page content
> -
> -

Ballerina Day form updated for the London event

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

> Updated the field order in the form
> -
> -

Updated the field order in the form

---

website/main-pages/ballerina.io-website-theme/js/ballerina-form.js

> Updated button text after submitting the form to improve UX

Updated button text

---

website/tools/build-bbe.sh

> Add missing BBE to the list temporarily
> Add missing BBE to the list temporarily
> -

Added missing BBE to the list

---

website/tools/ballerinaByExample/tools/generate.go

Update examples location

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

Update Ballerina Day 2018 London page content

---

website/two-column-pages/docs/learn/events/ballerina-day-colombo-2018.md

Update ballerina day 2018 page content update

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/two-column-pages/docs/learn/events.md

Update ballerina day banner

---

website/tools/ballerinaByExample/tools/generate.go

Update examples repository

---

website/two-column-pages/mkdocs.yml

Fix file name in yml

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

Update ballerina day agenda

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

> Updated the BBG label
> -
> -

Updated the BBG label

---

playground-widget/web/src/samples/data.json

Make hello-main-paralell the last one.

Reorder playground samples list

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

Update ballerina day speakers

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

Renamed AKS BBG

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

AKS BBG URL updated

---

website/tools/ballerinaByExample/tools/all-bbes.json

> Object Type Reference BBE added
> -
> -

Object Type Reference BBE added

---

website/two-column-pages/docs/learn/ballerina-streaming-reference.md

Fixed typo (recode -> record)

---

website/main-pages/ballerina.io-website-theme/base.html
website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

> Removed Ballerina Day registration - Updated the banner and the register button
> -
> -

Removed Ballerina Day registration

---

website/two-column-pages/docs/learn/getting-started.md

> Update paths and distribution names

Update paths and distribution names

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-cloud-native-programming-language.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-ecosystem.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-philosophy.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/data-integration.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/microservices-integration.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/orchestrating-microservices-with-docker-and-kubernetes.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/service-resiliency-in-microservices.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/writing-microservices.md
website/two-column-pages/mkdocs.yml

Update ballerina day London 2018 dummy pages

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-cloud-native-programming-language.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-ecosystem.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-philosophy.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/data-integration.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/microservices-integration.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/orchestrating-microservices-with-docker-and-kubernetes.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/service-resiliency-in-microservices.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/writing-microservices.md

> Updated bios, abstracts,  SM meta text, and SlideShare links

Update Ballerina Day UK pages with slides

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md

Changed tense in description to past tense. Removed registration text.

Update content to move to past events

---

website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-cloud-native-programming-language.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-ecosystem.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/ballerina-philosophy.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/microservices-integration.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/service-resiliency-in-microservices.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/writing-microservices.md
website/two-column-pages/docs/learn/events/past-events.md

Update video links and events page text.

Update videos and update past events page

---

website/main-pages/ballerina.io-website-theme/base.html
website/two-column-pages/docs/learn/events/ballerina-day-london-2018.md
website/two-column-pages/docs/learn/events/ballerina-day-london-2018/writing-microservices.md

Update ballerina day London pages

---

website/two-column-pages/docs/learn/ballerina-streaming-reference.md

Add refactoring fixes according to latest syntax changes

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

> Add info on entry points with public functions. Fixed syntax errors.

Fix deploy and run ballerina programs guide

---

website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md

This PR updates Ballerina syntax and bumps the Elastic Stack versions to 6.5.1

Update how to observe ballerina code to ballerina 0.990.0 version

---

website/two-column-pages/docs/community-program.md

> Updates the Ballerina Quick Tour – Community Engagement page with the new language syntax changes.

Update with new language syntax

---

website/two-column-pages/docs/learn/quick-tour.md

Adjust syntax and terminology to 0.990.0

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Update how to structure ballerina code

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Update 'How to Write Secure Ballerina Programs' guide to 0.990.0 syntax

Update 'How to Write Secure Ballerina Programs' guide to 0.990.0 syntax

---

website/two-column-pages/docs/learn/tools-ides.md

> Add compatibility section describing on how to enable the experimental features to support in tooling

Add compatibility section

---

website/tools/build-bbe.sh

> Adding new BBE repos for 0.990.0 release
> -
> -

Adding new BBE repos

---

.gitmodules
website/main-pages/ballerina.io-website-theme/js/philosophy.js
website/tools/ballerinaByExample/tools/all-bbes.json

> New BBG, BBE listing added for the release
> -
> -

0.990.0 release resources added

---

website/main-pages/ballerina.io-website-theme/js/philosophy.js

> Added LDAP integration BBG
> -
> -

Added LDAP integration BBG

---

.gitmodules

GKE BBG added

---

website/main-pages/ballerina.io-website-theme/js/download/archived_download.js

> Updated the archive sorting
> -
> -

Updated the archive sorting

---

website/main-pages/docs/downloads.md

> pack information updated
> -
> -

pack information updated

---

website/main-pages/docs/philosophy.md

Fix philosophy page BBG deployment section

---

website/main-pages/docs/philosophy.md

Fix philosophy page highlighting

---

api-docs/docs/ballerinax/jdbc.html

Update api docs - jdbc

---

website/main-pages/ballerina.io-website-theme/js/release_notes/all_release_notes.js

> ToC ordering updated
> -
> -

ToC ordering updated

---

website/two-column-pages/docs/community-program.md

Fix issues in code

---

.gitmodules
website/main-pages/ballerina.io-website-theme/js/philosophy.js

Added the SP BBG

---

website/two-column-pages/docs/learn.md

> To update the description of the "Tools and IDEs" section in [1].
[1] https://ballerina.io/learn/

Updating the "Tools and IDEs" section

---

website/tools/ballerinaByExample/tools/generate.go

> Processing markdown in BBE description files added
> -
> -

Processing markdown in BBE description files added

---

website/two-column-pages/docs/learn/tools-ides.md

Update tools and IDEs

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Remove try-catch in Testerina BBG sample

---

website/two-column-pages/docs/community-program.md

> Change Ballerina version in community program

Change ballerina version

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

Fix URL for ballerina config in https://ballerina.io/learn/how-to-deploy-and-run-ballerina-programs/

Fix URL for ballerina config

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

Update deploy-n-run guide

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Undo data validation change

---

website/two-column-pages/docs/learn/ballerina-streaming-reference.md

Additional detailed description for window impls

---

website/tools/ballerinaByExample/tools/all-bbes.json
website/tools/build-bbe.sh

> Updated BBE for 0.990.3 release
> -
> -

Updated BBE for 0.990.3 release

---

README.md

> Added MKDocs compatible version
> -
> -

Added MKDocs compatible version

---

website/two-column-pages/docs/deployment/aws-lambda.md

Update AWS page

---

.gitmodules
website/main-pages/ballerina.io-website-theme/js/philosophy.js

> New BBG added - AWS Lambda
> -
> -

New BBG added - AWS Lambda

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Remove run any function samples.
https://github.com/ballerina-platform/ballerina-lang/pull/13449

Remove run any function samples

---

api-docs/docs/ballerinax/module-list.html

Fix API docs navigation

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

Opening a new PR in place of #1338 
This PR updates "How to Extend Ballerina" with specific webhook implementation details.
https://github.com/ballerina-platform/ballerina-lang/pull/12938
https://github.com/wso2-ballerina/module-github/pull/66

Update how to extend Ballerina for specific webhooks

---

website/two-column-pages/docs/learn.md

Update language spec link

---

website/two-column-pages/docs/learn/events.md

Update events link

---

api-docs/docs/ballerinax/awslambda.html
api-docs/docs/ballerinax/module-list.html

Update AWS Lamda api docs

---

website/two-column-pages/docs/season-of-docs-2019.md

Add the initial content of the proposals.

Add the initial content of proposals

---

website/two-column-pages/docs/season-of-docs-2019.md

Fix list item display issue

---

website/two-column-pages/docs/season-of-docs-2019.md

Update sm description

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Update how-to-write-secure-ballerina-code.md file with Ballerina 0.991.0

Update secure ballerina learn material

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md
website/two-column-pages/docs/learn/how-to-test-ballerina-code.md
website/two-column-pages/docs/learn/quick-tour.md
website/two-column-pages/docs/learn/tools-ides.md

Update for v0.991.0 release

---

website/two-column-pages/docs/learn/tools-ides.md

> This will update the open api code generator guide link

Update open api guide link

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Introduce OAuth2 client config and hashing techniques for how-to-write-secure-ballerina-code.md

Introduce OAuth2 client config and hashing techniques

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md
website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md
website/two-column-pages/docs/learn/quick-tour.md

 Update for v0.991.0 release

---

website/two-column-pages/docs/learn/how-to-extend-ballerina.md

Fix WebSub Module.md link

---

website/two-column-pages/docs/learn/ballerina-streaming-reference.md

Change syntax to comply with latest spec changes

---

website/main-pages/ballerina.io-website-theme/samples/annotations.bal
website/main-pages/ballerina.io-website-theme/samples/api-constructs.bal
website/main-pages/ballerina.io-website-theme/samples/api-security.bal
website/main-pages/ballerina.io-website-theme/samples/network-data-types-and-conversions.bal
website/main-pages/ballerina.io-website-theme/samples/protocol-conversions.bal
website/main-pages/ballerina.io-website-theme/samples/resilient-communication.bal
website/main-pages/ballerina.io-website-theme/samples/service-composition.bal
website/main-pages/ballerina.io-website-theme/samples/services-and-resources.bal
website/main-pages/ballerina.io-website-theme/samples/transactions.bal

Update samples for 0.991.0

---

website/main-pages/docs/philosophy.md

This is to fix the typo "heterogenous" in the "Type-System" sub section under the "What are Ballerina's language design principles?" section.

Fix the typo "heterogenous"

---

website/tools/build-bbe.sh

> Updated Git repo for BBE
> -
> -

Updated Git repo for BBE

---

api-docs/docs/ballerinax/awslambda.html
api-docs/docs/ballerinax/docker.html
api-docs/docs/ballerinax/istio.html
api-docs/docs/ballerinax/jdbc.html
api-docs/docs/ballerinax/kubernetes.html

Update ballerinax breadcrumbs

---

website/two-column-pages/docs/learn/getting-started.md

This is to fix issues in displaying bullets in the below sections:
1. "Installing via the Ballerina language ZIP file" section (variable name and variable path)
2. In the note of the "Uninstalling Ballerina" section.

Fix display of bullets

---

api-docs/docs/ballerina/module-list.html

Fixed navigation

---

api-docs/docs/ballerina/module-list.html

Fix api docs navigation URLs

---

website/two-column-pages/docs/deployment/aws-lambda.md

Update aws lambda page for 0.991.0

---

website/tools/ballerinaByExample/tools/all-bbes.json

> Fixed a typo in the BBE list
> -
> -

Fixed a typo in the BBE labels

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

>This is to fix https://github.com/ballerina-platform/ballerina-www/issues/1423.

Fix issue #1423 in ballerina-www

---

website/two-column-pages/docs/learn/quick-tour.md

This is to fix https://github.com/ballerina-platform/ballerina-www/issues/1387.

Fix ballerina www issue 1387

---

website/two-column-pages/docs/learn/events.md

Update DevWeek NYC talk title

---

website/two-column-pages/docs/learn/events.md

Update Boston Meetup

---

website/two-column-pages/docs/learn.md

Adding the Ballerina style guide to the Ballerina website.

Adding the Ballerina style guide

---

website/two-column-pages/docs/learn.md

Reverts ballerina-platform/ballerina-www#1447

Revert "Adding the Ballerina style guide"

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Fix mobile issue

---

website/main-pages/docs/index.md

Update home page content

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

This is to document the usage of the "exclude-modules" flag in the "ballerina test" command.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/10832.
[1] https://ballerina.io/learn/how-to-test-ballerina-code/#writing-and-running-tests

Document the flag to exclude modules in the ballerina test command

---

website/two-column-pages/docs/learn/getting-started.md

Re organized content in section ""### Installing on Linux""

Reorganize content

---

website/two-column-pages/docs/learn/quick-tour.md

re organized content in the "Install Ballerina" section

---

playground-widget/resources/k8s/haproxy/rc.yaml

Update load balancer (HAProxy) SSL certs.

Update SSL certs in load balancer

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-api-new.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Add 1.0-alpha webiste

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/docs/index.md

Update alpha version

---

website/two-column-pages/docs/learn/how-to-document-ballerina-code.md

Update New Instructions to Generate Documentation

---

website/two-column-pages/docs/learn.md

Remove BBG

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update alpha version url

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

This is to update the new Testerina project structure in the B.io[1].
[1] https://ballerina.io/learn/how-to-test-ballerina-code/

Update the New Testerina Project Structure 

---

website/two-column-pages/docs/learn/quick-tour.md

Revamp quick-tour

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Fix How to Structure Ballerina Code

---

website/two-column-pages/docs/learn/quick-tour.md

Update quick tour

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Fix formatting issue

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/main-pages/mkdocs.yml

Remove Philosophy page from yml

---

website/two-column-pages/docs/learn/how-to-observe-ballerina-code.md

Update how-to-observe-ballerina-code.md for jBallerina alpha release

---

website/two-column-pages/docs/learn/quick-tour.md

This PR must go to alpha branch.

Revert "Revamp quick-tour"

---

website/two-column-pages/docs/learn.md

Update learn page for alpha release

---

website/two-column-pages/docs/learn.md

Update learn.md for alpha release

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update version selector

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io.css

Update version selector width

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin.md
website/two-column-pages/docs/learn/tools-ides/vscode-plugin.md

This is to fix broken images and numbered bullets in [1] & [2].
[1] https://ballerina.io/learn/tools-ides/intellij-plugin/
[2] https://ballerina.io/learn/tools-ides/vscode-plugin/
Fixes https://github.com/ballerina-platform/ballerina-www/issues/1474.

Fix Broken Images and Numbered Bullets

---

website/two-column-pages/docs/learn.md

This reverts commit d162af9890e51847bb5f9a62396a4b8caa0c145b.

Link api docs again. Revert "Update learn.md"

---

website/two-column-pages/docs/learn.md

Update spec link

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin.md

This is to add the compatibility schema mentioned in [1] to [2].
[1] https://github.com/ballerina-platform/ballerina-lang/tree/master/tool-plugins/intellij#release-versions-schema
[2] https://ballerina.io/learn/tools-ides/intellij-plugin/
Fixes https://github.com/ballerina-platform/ballerina-www/issues/1475.

Add the Compatibility Schema of IntelliJ

---

website/main-pages/ballerina.io-website-theme/base.html
website/main-pages/ballerina.io-website-theme/js/release_notes/all_release_notes.js
website/main-pages/mkdocs.yml
website/two-column-pages/ballerina.io-two-col-theme/base.html
website/two-column-pages/mkdocs.yml

> updated the release note json file
> -

updated the release note json file

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

> Added page path to the version drop down
> -

Added page path to the version drop down

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin.md
website/two-column-pages/docs/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
website/two-column-pages/docs/learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md

Fix broken links and images of IntelliJ docs

Fix Broken Links and Images of IntelliJ Docs

---

website/main-pages/ballerina.io-website-theme/base.html

Update SM image URL

---

website/main-pages/docs/index.md

Remove philosophy page link

---

website/main-pages/ballerina.io-website-theme/base.html

Update sm image

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Fix api docs sub menu

---

website/two-column-pages/docs/learn/quick-tour.md

Fix url in client

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Proofread the How to Structure Ballerina Code page

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Reverts ballerina-platform/ballerina-www#1516

Revert "Proofread the How to Structure Ballerina Code page"

---

website/main-pages/ballerina.io-website-theme/css/download-page.css
website/main-pages/ballerina.io-website-theme/js/ballerina-common.js

Update new theme

---

website/main-pages/ballerina.io-website-theme/img/search.svg
website/main-pages/mkdocs.yml
website/two-column-pages/mkdocs.yml

Update edit on git link

---

website/two-column-pages/docs/learn/tools-ides/vscode-plugin.md

Add instructions to reload VS Code

---

website/two-column-pages/docs/learn.md

Update learn page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-bbe.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io-learn.css
website/main-pages/ballerina.io-website-theme/img/white-arrow.svg
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/templates/index.tmpl
website/two-column-pages/docs/learn.md

Update BBE theme and Learn page

---

website/main-pages/docs/downloads.md
website/main-pages/docs/index.md
website/tools/ballerinaByExample/templates/example.tmpl
website/tools/ballerinaByExample/templates/index.tmpl
website/two-column-pages/docs/learn.md

1.0 rc1 Updated with new theme

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
website/two-column-pages/docs/learn/tools-ides/vscode-plugin/run-and-debug.md

Add information on debugging stepover.

Add information on debugging stepover

---

website/two-column-pages/docs/learn/style-guide.md

Adjust style guide's ballerina syntax to 1.0

---

website/two-column-pages/docs/learn/how-to-document-ballerina-code.md

Fix how to document ballerina

---

website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

$subject as we have removed the project level test directory

Remove info about project level test directory in how to structure Ballerina guide

---

website/main-pages/ballerina.io-website-theme/css/home-page.css
website/main-pages/ballerina.io-website-theme/img/main-go-icon-green.svg
website/main-pages/ballerina.io-website-theme/img/main-go-icon.svg
website/main-pages/docs/index.md
website/main-pages/mkdocs.yml
website/two-column-pages/mkdocs.yml

Home page update

---

website/main-pages/ballerina.io-website-theme/js/ballerina-common.js
website/two-column-pages/docs/learn.md

Update learn and credits

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

Update deploy guide

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Adjust testerina guide to ballerina 1.0 syntax

---

website/two-column-pages/docs/learn/how-to-test-ballerina-code.md

Update how to test Ballerina

---

website/two-column-pages/docs/learn/quick-tour.md

Update the quick tour

---

website/two-column-pages/docs/learn/getting-started.md

Adjust getting started guide to 1.0 syntax

---

website/two-column-pages/mkdocs.yml

This PR is to add entry to mkdocs yaml

Add entry to mkdocs yaml

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Update taint section of how-to-write-secure-ballerina-code guide

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
website/two-column-pages/docs/learn/tools-ides/vscode-plugin/run-and-debug.md

Add debugger troubleshooting guide

Add debugger troubleshooting guide

---

website/two-column-pages/docs/specs.md

Review the content of the `spec.md` file.

Review the `spec.md` file

---

website/main-pages/docs/index.md

Remove WebSub references and fix a typo

---

website/two-column-pages/docs/learn/how-to-deploy-and-run-ballerina-programs.md

Update org name

---

website/two-column-pages/docs/learn.md
website/two-column-pages/docs/learn/how-to-structure-ballerina-code.md

Minor fixes

---

website/main-pages/ballerina.io-website-theme/css/download-page.css

Update download page

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-docs.css
website/main-pages/ballerina.io-website-theme/css/ballerina-io.css
website/two-column-pages/docs/learn/tools-ides.md

Fix mobile issues

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
website/two-column-pages/docs/learn/tools-ides/vscode-plugin/run-and-debug.md

Update debugger troubleshooting guide

Update debugger troubleshooting guide

---

website/main-pages/ballerina.io-website-theme/css/ballerina-io-learn.css
website/two-column-pages/docs/learn.md
website/two-column-pages/docs/learn/events.md

fix learn page buttons

---

website/two-column-pages/docs/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
website/two-column-pages/docs/learn/tools-ides/vscode-plugin/run-and-debug.md

Update debugger troubleshooting

Update debugger troubleshooting

---

website/two-column-pages/docs/community.md

Fix slack link

---

website/two-column-pages/docs/learn/events.md

Fix events page

---

src/build.js
src/target/learn/how-to-deploy-and-run-ballerina-programs/index.html
src/target/learn/how-to-document-ballerina-code/index.html
src/target/learn/how-to-generate-code-for-protocol-buffers/index.html
src/target/learn/how-to-observe-ballerina-code/index.html
src/target/learn/how-to-publish-modules/index.html
src/target/learn/how-to-structure-ballerina-code/index.html
src/target/learn/how-to-test-ballerina-code/index.html
src/target/learn/style-guide/index.html
src/templates/learn/events.html
src/templates/learn/how-to-deploy-and-run-ballerina-programs.html
src/templates/learn/how-to-document-ballerina-code.html
src/templates/learn/how-to-generate-code-for-protocol-buffers.html
src/templates/learn/how-to-observe-ballerina-code.html
src/templates/learn/how-to-publish-modules.html
src/templates/learn/how-to-structure-ballerina-code.html
src/templates/learn/how-to-test-ballerina-code.html
src/templates/learn/style-guide.html
src/templates/learn/style-guide/definitions.html

Update 'How to' pages

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Add table of content for secure-doc

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Fix list issue

---

website/two-column-pages/docs/learn/how-to-write-secure-ballerina-code.md

Fix TOC of how to secure ballerina code page

---

website/two-column-pages/docs/learn/events.md

Remove October 8th event

---

website/two-column-pages/docs/learn/how-to-publish-modules.md

This is to improve and update the Learn page of B.io.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/18023.

Add Description of a Module When Publishing

---

README.md

Create the README.md for the repo
